# Generated by Django 5.0.2 on 2025-04-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_a',
            field=models.CharField(default='Option A', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b',
            field=models.CharField(default='Option B', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c',
            field=models.CharField(default='Option C', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(default='Option D', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
