# Generated by Django 5.0.2 on 2025-04-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_option_a_question_option_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='emotion_data_file',
            field=models.FileField(blank=True, null=True, upload_to='emotion_data/'),
        ),
    ]
