# Generated by Django 5.0.2 on 2025-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizattempt_emotion_data_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
    ]
