# Generated by Django 5.0.2 on 2025-04-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_points'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Points',
        ),
    ]
