# Generated by Django 5.0.2 on 2025-04-11 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('badge', models.CharField(choices=[('none', 'No Badge'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='none', max_length=10)),
                ('highest_streak', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('last_quiz_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
